server:
  port: 7072

spring:
  datasource:
##h2持久化时才需要配置
#    url: jdbc:h2:file:d:/h2/examples
#    #使用~标明位置 "~"这个符号代表的就是当前用户对应的用户目录
#    #url: jdbc:h2:file:~/.h2/examples
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver

#   hsqldb持久化时才需要配置
    url: jdbc:hsqldb:file:d:/hsqldb/examples
    username: sa
    password: sa
    driverClassName: org.hsqldb.jdbcDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    master:
      database: 1
#      host: 172.16.13.131
      port: 6379
      timeout: 2000
      password:
      pool:
        maxActive: 8
        minIdle: 0
        maxIdle: 8
        maxWait: -1
    slave:
      database: 1
#      host: 172.16.13.131
      port: 6380
      timeout: 2000
      password:
      pool:
        maxActive: 8
        minIdle: 0
        maxIdle: 8
        maxWait: -1

