server:
  port: 7072

spring:
  redis:
    master:
      database: 1
#      host: 172.16.13.131
      port: 6379
      timeout: 2000
      password:
      pool:
        maxActive: 8
        minIdle: 0
        maxIdle: 8
        maxWait: -1
    slave:
      database: 1
#      host: 172.16.13.131
      port: 6380
      timeout: 2000
      password:
      pool:
        maxActive: 8
        minIdle: 0
        maxIdle: 8
        maxWait: -1

